/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Artikal;
import domen.InterfaceObjekat;
import domen.PDVStopa;
import domen.StavkaPorudzbenice;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import transfer.ServerskiOdgovor;
import validator.ValidatorForme;

/**
 *
 * @author User
 */
public class FDodajStavku extends javax.swing.JDialog {

    /**
     * Creates new form FDodajStavku
     */
    public FDodajStavku(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniArtikle();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcomboartikal = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jtxtkolicina = new javax.swing.JTextField();
        jbtndodaj = new javax.swing.JButton();
        jbtnnazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Dodaj stavku");

        jLabel1.setText("Artikal:");

        jLabel2.setText("Kolicina:");

        jbtndodaj.setText("Dodaj");
        jbtndodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndodajActionPerformed(evt);
            }
        });

        jbtnnazad.setBackground(new java.awt.Color(255, 102, 102));
        jbtnnazad.setText("Nazad");
        jbtnnazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcomboartikal, 0, 255, Short.MAX_VALUE)
                    .addComponent(jtxtkolicina))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(jbtnnazad)
                .addGap(63, 63, 63)
                .addComponent(jbtndodaj)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcomboartikal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jtxtkolicina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtndodaj)
                    .addComponent(jbtnnazad))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnnazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnazadActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jbtnnazadActionPerformed

    private void jbtndodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndodajActionPerformed
        // TODO add your handling code here:
        boolean validno = ValidatorForme.getInstanca().validacijaPolja(jtxtkolicina);
        if (!validno) {
            JOptionPane.showMessageDialog(this, ValidatorForme.getInstanca().getPoruka(), "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Artikal a = (Artikal) jcomboartikal.getSelectedItem();
        int kolicina = Integer.parseInt(jtxtkolicina.getText());
        if (kolicina == 0 || kolicina < 0) {
            JOptionPane.showMessageDialog(this, "Kolicina ne sme biti negativna niti jednaka nuli! ", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        double ukupnosapdvom = kolicina * a.getCenaArtiklaSaPdvom();
        double ukupnobezpdva = kolicina * a.getCenaArtiklaBezPdva();
        StavkaPorudzbenice sp = new StavkaPorudzbenice(-1, kolicina, ukupnosapdvom, ukupnobezpdva, a, null);
        FKreirajPorudzbenicu fkp = (FKreirajPorudzbenicu) getParent();
        fkp.dodajStavku(sp);
        jtxtkolicina.setText("");
    }//GEN-LAST:event_jbtndodajActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FDodajStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FDodajStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FDodajStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FDodajStavku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FDodajStavku dialog = new FDodajStavku(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbtndodaj;
    private javax.swing.JButton jbtnnazad;
    private javax.swing.JComboBox<domen.Artikal> jcomboartikal;
    private javax.swing.JTextField jtxtkolicina;
    // End of variables declaration//GEN-END:variables

    private void popuniArtikle() {
        ServerskiOdgovor so = Kontroler.getInstanca().vratiArtikle();

        if (so.isUspesno()) {
            List<InterfaceObjekat> lista = (List<InterfaceObjekat>) so.getOdgovor();
            jcomboartikal.removeAllItems();
            for (InterfaceObjekat objekat : lista) {
                jcomboartikal.addItem((Artikal) objekat);
            }
        } else {
            JOptionPane.showMessageDialog(this, so.getPoruka(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }
}
