/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.InterfaceObjekat;
import domen.Korisnik;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import threads.ThreadClock;

/**
 *
 * @author User
 */
public class FGlavniMeni extends javax.swing.JFrame {

    InterfaceObjekat korisnik;
    Korisnik k;

    /**
     * Creates new form GlavniMeni
     */
    public FGlavniMeni() {
        initComponents();
        setLocationRelativeTo(null);
        fill();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabkorisnik = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlabDate = new javax.swing.JLabel();
        jlabTime = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jartikli1 = new javax.swing.JMenuItem();
        jartikli2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jporudz1 = new javax.swing.JMenuItem();
        jporud2 = new javax.swing.JMenuItem();
        jmenugrafik = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Glavni meni");

        jPanel1.setBackground(new java.awt.Color(245, 178, 13));

        jlabkorisnik.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jlabkorisnik.setText("jLabel1");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/kaficanovooooo.jpg"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jLabel2.setText("jLabel2");

        jlabDate.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jlabDate.setText("jLabel3");

        jlabTime.setFont(new java.awt.Font("Traditional Arabic", 0, 18)); // NOI18N
        jlabTime.setText("jLabel3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel1)
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabTime, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabDate, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jlabkorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlabDate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jlabkorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlabTime, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu1.setText("Artikli");

        jartikli1.setText("Kreiranje");
        jartikli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jartikli1ActionPerformed(evt);
            }
        });
        jMenu1.add(jartikli1);

        jartikli2.setText("Izmena, brisanje i pretraga");
        jartikli2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jartikli2ActionPerformed(evt);
            }
        });
        jMenu1.add(jartikli2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Porudzbenice");

        jporudz1.setText("Kreiraj");
        jporudz1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jporudz1ActionPerformed(evt);
            }
        });
        jMenu2.add(jporudz1);

        jporud2.setText("Prikaz i brisanje");
        jporud2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jporud2ActionPerformed(evt);
            }
        });
        jMenu2.add(jporud2);

        jmenugrafik.setText("Grafik sale");
        jmenugrafik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmenugrafikActionPerformed(evt);
            }
        });
        jMenu2.add(jmenugrafik);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jartikli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jartikli1ActionPerformed
        // TODO add your handling code here:
        FKreirajArtikal fa = new FKreirajArtikal(this, true);
        fa.pack();
        fa.setKorisnik(k);
        fa.setVisible(true);
    }//GEN-LAST:event_jartikli1ActionPerformed

    private void jartikli2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jartikli2ActionPerformed
        // TODO add your handling code here:
        FRadSaArtiklima fr = new FRadSaArtiklima();
        fr.setVisible(true);
        this.setVisible(false);
        fr.setGlavniMeni(this);
    }//GEN-LAST:event_jartikli2ActionPerformed

    private void jporudz1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jporudz1ActionPerformed
        // TODO add your handling code here:
        FKreirajPorudzbenicu fp = new FKreirajPorudzbenicu(korisnik, this);
        fp.srediZaUnos();
        fp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jporudz1ActionPerformed

    private void jporud2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jporud2ActionPerformed
        // TODO add your handling code here:
        FRadSaPorudzbenicama fpp = new FRadSaPorudzbenicama(k);
        fpp.setVisible(true);
        this.setVisible(false);
        fpp.setGlavna(this);
    }//GEN-LAST:event_jporud2ActionPerformed

    private void jmenugrafikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmenugrafikActionPerformed
        // TODO add your handling code here:
        FIzaberiSto fs = new FIzaberiSto(this, true, true);
        fs.setVisible(true);
    }//GEN-LAST:event_jmenugrafikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FGlavniMeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FGlavniMeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FGlavniMeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FGlavniMeni.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FGlavniMeni().setVisible(true);
            }
        });
    }

    void setKorisnika(InterfaceObjekat korisnik) {
        this.korisnik = korisnik;
        k = (Korisnik) korisnik;
        jLabel2.setText("Dobrodosli dragi korisnice, trenutno vreme je: ");
        jlabkorisnik.setText("Ulogovani korisnik je: " + k.getIme() + " " + k.getPrezime());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jartikli1;
    private javax.swing.JMenuItem jartikli2;
    private javax.swing.JLabel jlabDate;
    private javax.swing.JLabel jlabTime;
    private javax.swing.JLabel jlabkorisnik;
    private javax.swing.JMenuItem jmenugrafik;
    private javax.swing.JMenuItem jporud2;
    private javax.swing.JMenuItem jporudz1;
    // End of variables declaration//GEN-END:variables

    private void fill() {
        ThreadClock clock = new ThreadClock(this);
        clock.start();

    }

    public void showDate() {
        Date datum = new Date();
        SimpleDateFormat sf1 = new SimpleDateFormat("dd.MM.yyyy.");
        String datumString = sf1.format(datum);
        jlabDate.setText(datumString);

        SimpleDateFormat sf = new SimpleDateFormat("HH:mm:ss");
        String timeString = sf.format(datum);
        jlabTime.setText(timeString);
    }
}
