/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Artikal;
import domen.InterfaceObjekat;
import domen.JedinicaMere;
import domen.PDVStopa;
import static java.lang.Character.isDigit;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import kontroler.Kontroler;
import modelitabela.ModelTabeleArtikli;
import transfer.ServerskiOdgovor;
import validator.ValidatorForme;

/**
 *
 * @author User
 */
public class FIzmenaArtikla extends javax.swing.JDialog {

    Artikal a;

    /**
     * Creates new form FIzmenaArtikla
     */
    public FIzmenaArtikla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    public FIzmenaArtikla(java.awt.Frame parent, boolean modal, Artikal a) {
        super(parent, modal);
        initComponents();
        this.a = a;
        JOptionPane.showMessageDialog(this, "Sistem je prikazao izabrani artikal");
        popuniJedinicuMere();
        popuniPdvStope();
        poljaForme();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jlabkorisnik = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtnaziv = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtcenasa = new javax.swing.JTextField();
        jtxtcenabez = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jcombojedinica = new javax.swing.JComboBox<>();
        jcombopdv = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jbtnizmeni = new javax.swing.JButton();
        jbtnodustani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Izmena artikla");

        jLabel1.setText("Korisnik:");

        jlabkorisnik.setText("jLabel2");

        jLabel2.setText("Naziv artikla:");

        jLabel3.setText("Cena artikla sa pdv-om:");

        jtxtcenasa.setEnabled(false);

        jLabel4.setText("Cena artikla bez pdv-a:");

        jLabel5.setText("Jedinica mere:");

        jLabel6.setText("PDV Stopa:");

        jbtnizmeni.setText("Izmeni");
        jbtnizmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnizmeniActionPerformed(evt);
            }
        });

        jbtnodustani.setBackground(new java.awt.Color(255, 102, 102));
        jbtnodustani.setForeground(new java.awt.Color(255, 255, 255));
        jbtnodustani.setText("Odustani");
        jbtnodustani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnodustaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtnaziv)
                            .addComponent(jlabkorisnik, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtcenasa)
                            .addComponent(jtxtcenabez, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                            .addComponent(jcombojedinica, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jcombopdv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnodustani)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnizmeni)
                        .addGap(63, 63, 63))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlabkorisnik))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtnaziv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtcenasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtcenabez, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcombojedinica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jcombopdv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnizmeni)
                    .addComponent(jbtnodustani))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnodustaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnodustaniActionPerformed
        // TODO add your handling code here:
        FRadSaArtiklima fa = (FRadSaArtiklima) getParent();
        fa.refresh();
        this.dispose();

    }//GEN-LAST:event_jbtnodustaniActionPerformed

    private void jbtnizmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnizmeniActionPerformed
        // TODO add your handling code here:
        boolean valid = ValidatorForme.getInstanca().validacijaPolja(jtxtcenabez, jtxtnaziv);
        if (!valid) {
            JOptionPane.showMessageDialog(this, ValidatorForme.getInstanca().getPoruka(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
        double cena = 0;
        String naziv = jtxtnaziv.getText();
        valid = true;
        for (char c : naziv.toCharArray()) {
            if (isDigit(c)) {
                valid = false;
            }
        }
        if (valid == false) {
            JOptionPane.showMessageDialog(this, "Naziv ne sme sadrzati cifre", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            cena = Double.parseDouble(jtxtcenabez.getText());
            if (cena == 0) {
                return;
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Cena mora biti broj", "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String jmS = (String) jcombojedinica.getSelectedItem();
        JedinicaMere jm = JedinicaMere.valueOf(jmS);

        PDVStopa ps = (PDVStopa) jcombopdv.getSelectedItem();

        double iznos = ps.getIznos();
        double cenasa = cena * (1 + (iznos / 100));

        jtxtcenasa.setText(Double.toString(cenasa));

        Artikal novi = new Artikal(a.getArtikalid(), naziv, cenasa, cena, jm, a.getKorisnik(), ps);

        ServerskiOdgovor so = Kontroler.getInstanca().izmeniArtikal(novi);

        if (so.isUspesno()) {
            JOptionPane.showMessageDialog(this, "Sistem je izmenio artikal");
            FRadSaArtiklima fa = (FRadSaArtiklima) getParent();
            fa.refresh();

        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da izmeni artikal", "Greska", JOptionPane.ERROR_MESSAGE);

        }


    }//GEN-LAST:event_jbtnizmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FIzmenaArtikla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FIzmenaArtikla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FIzmenaArtikla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FIzmenaArtikla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FIzmenaArtikla dialog = new FIzmenaArtikla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void popuniJedinicuMere() {
        jcombojedinica.removeAllItems();
        List<String> lista = new ArrayList<>();
        lista.add("kom");
        lista.add("ml");
        for (String string : lista) {
            jcombojedinica.addItem(string);
        }
    }

    private void popuniPdvStope() {
        ServerskiOdgovor so = Kontroler.getInstanca().VratiPdvStope();

        if (so.isUspesno()) {
            List<InterfaceObjekat> lista = (List<InterfaceObjekat>) so.getOdgovor();
            jcombopdv.removeAllItems();
            for (InterfaceObjekat objekat : lista) {
                jcombopdv.addItem((PDVStopa) objekat);
            }
        } else {
            JOptionPane.showMessageDialog(this, so.getPoruka(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnizmeni;
    private javax.swing.JButton jbtnodustani;
    private javax.swing.JComboBox<String> jcombojedinica;
    private javax.swing.JComboBox<domen.PDVStopa> jcombopdv;
    private javax.swing.JLabel jlabkorisnik;
    private javax.swing.JTextField jtxtcenabez;
    private javax.swing.JTextField jtxtcenasa;
    private javax.swing.JTextField jtxtnaziv;
    // End of variables declaration//GEN-END:variables

    private void poljaForme() {
        jtxtnaziv.setText(a.getNazivArtikla());
        jtxtcenasa.setText(Double.toString(a.getCenaArtiklaSaPdvom()));
        jtxtcenabez.setText(Double.toString(a.getCenaArtiklaBezPdva()));
        jlabkorisnik.setText(a.getKorisnik().getIme() + " " + a.getKorisnik().getPrezime());
        jcombojedinica.setSelectedItem(a.getJedinicaMere().toString());
        jcombopdv.setSelectedItem(a.getPdvStopa());
    }
}
