/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.InterfaceObjekat;
import domen.Korisnik;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import povezivanje.Komunikacija;
import threads.ThreadClock;
import transfer.ServerskiOdgovor;
import validator.ValidatorForme;

/**
 *
 * @author User
 */
public class FLogin extends javax.swing.JFrame {

    /**
     * Creates new form FLogin
     */
    public FLogin() {
        initComponents();
        setLocationRelativeTo(null);
        fill();
        try {
            Komunikacija.getInstance().poveziSe();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Klijent ne moze da se poveze na server. Program ce se prekinuti", "Greska", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelLogIn = new javax.swing.JPanel();
        jlabUser = new javax.swing.JLabel();
        jlabPassword = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jtxtPassword = new javax.swing.JPasswordField();
        jlabImg = new javax.swing.JLabel();
        jbtnLogin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlabTime = new javax.swing.JLabel();
        jlabDate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");

        jPanelLogIn.setBackground(new java.awt.Color(245, 178, 13));

        jlabUser.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jlabUser.setText("username: ");

        jlabPassword.setFont(new java.awt.Font("Traditional Arabic", 0, 14)); // NOI18N
        jlabPassword.setText("password:");

        jlabImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/coffeeNew.png"))); // NOI18N

        jbtnLogin.setBackground(new java.awt.Color(246, 213, 132));
        jbtnLogin.setFont(new java.awt.Font("Traditional Arabic", 0, 16)); // NOI18N
        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 1, 36)); // NOI18N
        jLabel1.setText("Nautilus");

        jlabTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlabTime.setText("jLabel2");

        jlabDate.setText("jLabel2");

        javax.swing.GroupLayout jPanelLogInLayout = new javax.swing.GroupLayout(jPanelLogIn);
        jPanelLogIn.setLayout(jPanelLogInLayout);
        jPanelLogInLayout.setHorizontalGroup(
            jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogInLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jlabImg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLogInLayout.createSequentialGroup()
                        .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlabPassword)
                            .addComponent(jlabUser))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                            .addComponent(jtxtPassword)))
                    .addComponent(jbtnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(121, 121, 121))
            .addGroup(jPanelLogInLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabTime, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(179, 179, 179))
        );
        jPanelLogInLayout.setVerticalGroup(
            jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogInLayout.createSequentialGroup()
                .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLogInLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jlabImg, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelLogInLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jlabDate)
                        .addGap(18, 18, 18)
                        .addComponent(jlabTime, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLogInLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jlabUser)
                                    .addComponent(jtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelLogInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jlabPassword)
                                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelLogInLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                                .addComponent(jbtnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        // TODO add your handling code here:
        boolean val = ValidatorForme.getInstanca().validacijaPolja(jtxtUsername, jtxtPassword);
        if (!val) {
            JOptionPane.showMessageDialog(this, ValidatorForme.getInstanca().getPoruka(), "Greska", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String username = jtxtUsername.getText();
        String password = String.valueOf(jtxtPassword.getPassword());
        for (char k : username.toCharArray()) {
            if (Character.isDigit(k)) {
                JOptionPane.showMessageDialog(this, "Korisnicko ime ne sme da pocinje cifrom", "Greska", JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        if (password.length() < 4) {
            JOptionPane.showMessageDialog(this, "Sifra mora da ima minimum 4 karaktera", "Greska", JOptionPane.ERROR_MESSAGE);
            return;            
        }
        Korisnik k = new Korisnik();
        k.setUsername(username);
        k.setPassword(password);
        
        ServerskiOdgovor so = Kontroler.getInstanca().prijaviNaSistem(k);
        
        if (so.isUspesno()) {
            JOptionPane.showMessageDialog(this, so.getPoruka());
            FGlavniMeni gf = new FGlavniMeni();
            gf.setKorisnika((InterfaceObjekat) so.getOdgovor());
            gf.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, so.getPoruka(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelLogIn;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JLabel jlabDate;
    private javax.swing.JLabel jlabImg;
    private javax.swing.JLabel jlabPassword;
    private javax.swing.JLabel jlabTime;
    private javax.swing.JLabel jlabUser;
    private javax.swing.JPasswordField jtxtPassword;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables

    private void fill() {
        ThreadClock clock = new ThreadClock(this);
        clock.start();
        
    }
    
    public void showDate() {
        Date datum = new Date();
        SimpleDateFormat sf1 = new SimpleDateFormat("dd.MM.yyyy.");
        String datumString = sf1.format(datum);
        jlabDate.setText(datumString);
        
        SimpleDateFormat sf = new SimpleDateFormat("HH:mm:ss");
        String timeString = sf.format(datum);
        jlabTime.setText(timeString);
    }
    
}
