/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Artikal;
import domen.InterfaceObjekat;
import domen.Korisnik;
import domen.Porudzbenica;
import domen.StavkaPorudzbenice;
import domen.Sto;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modelitabela.ModelTabeleArtikli;
import modelitabela.ModelTabelePorudzbenice;
import transfer.ServerskiOdgovor;

/**
 *
 * @author User
 */
public class FRadSaPorudzbenicama extends javax.swing.JFrame {

    FGlavniMeni gm;
    Korisnik k;

    /**
     * Creates new form FRadSaPorudzbenicama
     */
    public FRadSaPorudzbenicama() {
        initComponents();
        setLocationRelativeTo(null);
        jtblporudzbenice.setModel(new ModelTabelePorudzbenice());
        prikaziPorudzbenice();
    }

    FRadSaPorudzbenicama(Korisnik k) {
        initComponents();
        setLocationRelativeTo(null);
        jtblporudzbenice.setModel(new ModelTabelePorudzbenice());
        prikaziPorudzbenice();
        this.k=k;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtdatum = new javax.swing.JTextField();
        jbtnpretrazi = new javax.swing.JButton();
        jbtndetalji = new javax.swing.JButton();
        jbtnobrisi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblporudzbenice = new javax.swing.JTable();
        jbtnglavnimeni = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rad sa porudzbenicama");

        jPanel1.setBackground(new java.awt.Color(250, 202, 82));

        jLabel1.setText("Pretraga po datumu: ");

        jbtnpretrazi.setText("Pretrazi");
        jbtnpretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpretraziActionPerformed(evt);
            }
        });

        jbtndetalji.setText("Detaljno");
        jbtndetalji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndetaljiActionPerformed(evt);
            }
        });

        jbtnobrisi.setText("Obrisi");
        jbtnobrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnobrisiActionPerformed(evt);
            }
        });

        jtblporudzbenice.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblporudzbenice);

        jbtnglavnimeni.setText("Glavni meni");
        jbtnglavnimeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnglavnimeniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnobrisi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtndetalji, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxtdatum, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbtnpretrazi))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jbtnglavnimeni)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnpretrazi))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jbtndetalji)
                        .addGap(53, 53, 53)
                        .addComponent(jbtnobrisi))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnglavnimeni)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnglavnimeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnglavnimeniActionPerformed
        // TODO add your handling code here:
        gm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnglavnimeniActionPerformed

    private void jbtnobrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnobrisiActionPerformed
        // TODO add your handling code here:
        int red = jtblporudzbenice.getSelectedRow();
        if(red != -1){
        ModelTabelePorudzbenice mtp = (ModelTabelePorudzbenice) jtblporudzbenice.getModel();
        Porudzbenica p = mtp.dajPorudzbenicu(red);

        int response = JOptionPane.showConfirmDialog(this, "Da li sigurno zelite da obrisete izabranu porudzbenicu?", "Brisanje racuna", JOptionPane.YES_NO_OPTION);
        if (response == JOptionPane.OK_OPTION) {
            ServerskiOdgovor so = Kontroler.getInstanca().obrisiPorudzbenicu(p);

            if (so.isUspesno()) {
                JOptionPane.showMessageDialog(this, so.getPoruka(), "Uspesno", JOptionPane.INFORMATION_MESSAGE);
                prikaziPorudzbenice();
            } else {
                JOptionPane.showMessageDialog(this, so.getPoruka(), "Neuspesno", JOptionPane.ERROR_MESSAGE);
            }
        }

        Sto s = p.getSto();

        byte stat = 0;
        s.setStatus(stat);
        ServerskiOdgovor so1 = Kontroler.getInstanca().izmeniSto(s);

        if (so1.isUspesno()) {
            JOptionPane.showMessageDialog(this, "Sto vise nije zauzet");
            mtp.refresh();
        } else {
            JOptionPane.showMessageDialog(this, "Greska kod oslobadjanja stola");
        }
        }else {
           JOptionPane.showMessageDialog(this, "Sistem ne moze da obrise proizvod", "Greska", JOptionPane.ERROR_MESSAGE);
          
        }
//        StavkaPorudzbenice sp = new StavkaPorudzbenice();
//        sp.setPorudzbenica(p);
//        ServerskiOdgovor so2 = Kontroler.getInstanca().obrisiStavke(sp);
//
//        if (so2.isUspesno()) {
//            JOptionPane.showMessageDialog(this, "Stavke su obrisane");
//        } else {
//            JOptionPane.showMessageDialog(this, "Greska kod brisanja stavki");
//        }

    }//GEN-LAST:event_jbtnobrisiActionPerformed

    private void jbtnpretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpretraziActionPerformed
        // TODO add your handling code here:
        srediTabelu();
    }//GEN-LAST:event_jbtnpretraziActionPerformed

    private void jbtndetaljiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndetaljiActionPerformed
        // TODO add your handling code here:
        int red = jtblporudzbenice.getSelectedRow();
        ModelTabelePorudzbenice mtp = (ModelTabelePorudzbenice) jtblporudzbenice.getModel();

        if (red != -1) {
            Porudzbenica p = mtp.dajPorudzbenicu(red);
            FKreirajPorudzbenicu fk = new FKreirajPorudzbenicu(p.getKorisnik(), gm,"detalji");
            fk.setForma(this);
            fk.srediFormuZaDetalje(p);
            fk.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jbtndetaljiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRadSaPorudzbenicama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRadSaPorudzbenicama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRadSaPorudzbenicama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRadSaPorudzbenicama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRadSaPorudzbenicama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtndetalji;
    private javax.swing.JButton jbtnglavnimeni;
    private javax.swing.JButton jbtnobrisi;
    private javax.swing.JButton jbtnpretrazi;
    private javax.swing.JTable jtblporudzbenice;
    private javax.swing.JTextField jtxtdatum;
    // End of variables declaration//GEN-END:variables

    void setGlavna(FGlavniMeni aThis) {
        this.gm = aThis;
    }

    private void prikaziPorudzbenice() {
        Porudzbenica p = new Porudzbenica();
        p.setDatumPorudzbenice(null);

        ServerskiOdgovor so = Kontroler.getInstanca().pretraziPorudzbenice(p);

        if (so.isUspesno()) {
            List<InterfaceObjekat> listaPorudzbenica = (List<InterfaceObjekat>) so.getOdgovor();
            if (listaPorudzbenica.isEmpty()) {
                return;
            }
            ModelTabelePorudzbenice mtp = new ModelTabelePorudzbenice();
            mtp.setLista(listaPorudzbenica);
            jtblporudzbenice.setModel(mtp);
        } else {
            JOptionPane.showMessageDialog(this, "Sistem nije pronasao porudzbenice");
        }
    }

    private void srediTabelu() {
        String dat = jtxtdatum.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        try {
            Date datum = sdf.parse(dat);
            Porudzbenica p = new Porudzbenica();
            p.setDatumPorudzbenice(datum);

            ServerskiOdgovor so = Kontroler.getInstanca().pretraziPorudzbenice(p);

            if (so.isUspesno()) {
                List<InterfaceObjekat> listaPor = (List<InterfaceObjekat>) so.getOdgovor();
                if (listaPor.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Sistem nije pronasao porudzbenice po zadatim kriterijumima pretrage");
                    return;
                }
                ModelTabelePorudzbenice mtp = new ModelTabelePorudzbenice();
                mtp.setLista(listaPor);
                jtblporudzbenice.setModel(mtp);
                JOptionPane.showMessageDialog(this, "Sistem je pronasao porudzbenice po zadatim kriterijumima pretrage");
            } else {
                JOptionPane.showMessageDialog(this, "Sistem nije pronasao porudzbenice po zadatim kriterijumima pretrage");
            }

        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Datum nije u dobrom formatu", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

   

}
