/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import domen.Artikal;
import domen.InterfaceObjekat;
import java.util.List;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import modelitabela.ModelTabeleArtikli;
import modelitabela.ModelTabelePorudzbenice;
import threads.NitRefresh;
import transfer.ServerskiOdgovor;

/**
 *
 * @author User
 */
public class FRadSaArtiklima extends javax.swing.JFrame {

    FGlavniMeni fm;
    NitRefresh nit;
    int tab;

    /**
     * Creates new form FRadSaArtiklima
     */
    public FRadSaArtiklima() {
        initComponents();
        setLocationRelativeTo(null);
        sreditabelu();
        nit = new NitRefresh(this);
        nit.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jbtnpretrazi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jbtnizmeni = new javax.swing.JButton();
        jbtnobrisi = new javax.swing.JButton();
        jbtnnazad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rad sa artiklima");
        setBackground(new java.awt.Color(255, 204, 204));
        setForeground(new java.awt.Color(255, 204, 204));

        jPanel1.setBackground(new java.awt.Color(250, 202, 82));

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 12)); // NOI18N
        jLabel1.setText("Pretraga po nazivu: ");

        jbtnpretrazi.setFont(new java.awt.Font("Traditional Arabic", 0, 12)); // NOI18N
        jbtnpretrazi.setText("Pretrazi");
        jbtnpretrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnpretraziActionPerformed(evt);
            }
        });

        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jbtnizmeni.setFont(new java.awt.Font("Traditional Arabic", 0, 12)); // NOI18N
        jbtnizmeni.setText("Izmeni");
        jbtnizmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnizmeniActionPerformed(evt);
            }
        });

        jbtnobrisi.setFont(new java.awt.Font("Traditional Arabic", 0, 12)); // NOI18N
        jbtnobrisi.setText("Obrisi");
        jbtnobrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnobrisiActionPerformed(evt);
            }
        });

        jbtnnazad.setBackground(new java.awt.Color(255, 102, 102));
        jbtnnazad.setFont(new java.awt.Font("Traditional Arabic", 0, 12)); // NOI18N
        jbtnnazad.setText("Nazad");
        jbtnnazad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnnazadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnpretrazi)
                        .addGap(38, 38, 38)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jbtnnazad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnizmeni)
                .addGap(51, 51, 51)
                .addComponent(jbtnobrisi)
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnpretrazi))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jbtnnazad))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtnizmeni)
                            .addComponent(jbtnobrisi))))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnnazadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnnazadActionPerformed
        // TODO add your handling code here:
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnnazadActionPerformed

    private void jbtnpretraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnpretraziActionPerformed
        // TODO add your handling code here:
        nit.setStatus();
        srediTabelu2();
        poruka(tab);

    }//GEN-LAST:event_jbtnpretraziActionPerformed

    private void jbtnobrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnobrisiActionPerformed
        // TODO add your handling code here:
        int red = jTable2.getSelectedRow();
        if (red != -1) {
            ModelTabeleArtikli mta = (ModelTabeleArtikli) jTable2.getModel();
            Artikal a = mta.vratiSelektovaniArtikal(red);
            int response = JOptionPane.showConfirmDialog(this, "Da li sigurno zelite da obrisete artikal " + a + "?", "Brisanje artikla", JOptionPane.YES_NO_OPTION);
            if (response == JOptionPane.OK_OPTION) {

                ServerskiOdgovor so = Kontroler.getInstanca().obrisiArtikal(a);

                if (so.isUspesno()) {
                    JOptionPane.showMessageDialog(this, so.getPoruka(), "Uspesno", JOptionPane.INFORMATION_MESSAGE);
                    sreditabelu();

                } else {
                    JOptionPane.showMessageDialog(this, so.getPoruka(), "Neuspesno", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Sistem nije obrisao artikal", "Greska", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jbtnobrisiActionPerformed

    private void jbtnizmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnizmeniActionPerformed
        // TODO add your handling code here:
        int red = jTable2.getSelectedRow();

        if (red != -1) {
            ModelTabeleArtikli mta = (ModelTabeleArtikli) jTable2.getModel();
            Artikal a = mta.vratiSelektovaniArtikal(red);
            FIzmenaArtikla iaf = new FIzmenaArtikla(this, true, a);
            iaf.pack();
            iaf.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(this, "Sistem ne moze da prikaze artikal po zadatoj vrednosti", "Greska", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jbtnizmeniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRadSaArtiklima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRadSaArtiklima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRadSaArtiklima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRadSaArtiklima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRadSaArtiklima().setVisible(true);
            }
        });
    }

    void setGlavniMeni(FGlavniMeni fm) {
        this.fm = fm;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jbtnizmeni;
    private javax.swing.JButton jbtnnazad;
    private javax.swing.JButton jbtnobrisi;
    private javax.swing.JButton jbtnpretrazi;
    // End of variables declaration//GEN-END:variables

    public void sreditabelu() {
        Artikal a = new Artikal();
        a.setNazivArtikla("");

        ServerskiOdgovor so = Kontroler.getInstanca().pronadjiArtikle(a);

        if (so.isUspesno()) {
            List<InterfaceObjekat> listaArtikla = (List<InterfaceObjekat>) so.getOdgovor();
            ModelTabeleArtikli mta = new ModelTabeleArtikli();
            mta.setLista(listaArtikla);
            jTable2.setModel(mta);
        } else {
            JOptionPane.showMessageDialog(this, "Neuspesno ucitana lista artikala", "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }

    void refresh() {
        ModelTabeleArtikli mtp = (ModelTabeleArtikli) jTable2.getModel();
        mtp.refresh();
    }

    public void srediTabelu2() {
        Artikal a = new Artikal();
        a.setNazivArtikla(jTextField1.getText());

        ServerskiOdgovor so = Kontroler.getInstanca().pronadjiArtikle(a);

        if (so.isUspesno()) {
            List<InterfaceObjekat> listaartikala = (List<InterfaceObjekat>) so.getOdgovor();
            ModelTabeleArtikli mta = (ModelTabeleArtikli) jTable2.getModel();
            mta.setLista(listaartikala);
            if (listaartikala.isEmpty()) {
                tab = 0;

            } else {
                tab = 1;

            }
        } else {
            tab = 2;

        }
    }

    private void poruka(int tab) {
        switch (tab) {
            case 0:
                JOptionPane.showMessageDialog(this, "Sistem ne moze da pronadje artikle po zadatim kriterijumima pretrage");
                break;
            case 1:
                JOptionPane.showMessageDialog(this, "Sistem je pronasao artikle po zadatim kriterijumima pretrage");
                break;
            case 2:
                JOptionPane.showMessageDialog(this, "Sistem ne moze da pronadje artikle po zadatim kriterijumima pretrage");
                break;
        }
    }

}
